os: "linux",
sudo: enabled
language: node_js
node_js:
  - "node"
  - "8"
install:
    - npm install
    - npm install mocha -g
script:
    - node -v
    - node server/service.js
    - node test/test.js